language: go

env:
  global:
    - GO111MODULE=on

install:
  - make bootstrap

script:
  - go version
  - make build
  - make install
  - make test

before_deploy:
  - make xbuild archive

deploy:
  provider: releases
  api_key:
    secure: oqN6gDxXvENCwOSRgJ5tjdmqRTlgw2wsfNxThEVFiTG3+0yklAsp1A9/K8a8d3GpxeVMTSLoVosscrge61YxCq9CfPg7UAhMsPa4BdBeOC+9H1Sys/7RJWbiJgkDm7Vy2FkjPhD5En19oCzmO1H/47tenUGo6pxUdFSHvBt1G2+8O88pE/IewprCV8dnybSw70v81EesZugPq74VO36Lz7m7uNnNx5YWcb4wuxVoJZhqKnZsyJq0uDbsoe310G+PyxlGvRxXKoI4nRB8nKnjVGv9+EISm3ChT5u1AzqN6acCqUcuHb2ULuBcHato/9UuADCOVW/0LMvR24mEmpcj03QdOhAhgVrOwLjPN+LNIUrzi3AUVUlSPAS7JzOdNYBQoFQABy9ymvLynzYS9uIhDlytsofUtzljLOtIiJ3kNLDBexRxw+ACsRdU4I9KhoBBWe/0ThHFA8IDIgAVXASKK7z9YhcFJnW8/ZnTz8QKxek4zTrvVjYlpIC0sCbaQGDf9fzH4Np5un5XtG2agOilmL7gO+b7CvylwbRwoBjdXfP33YTVphQmMr+vVbJ9VJzvxYzvZtnnZCIGvj+D5wGOqHcnvIKWNC9snCyJKUTvfDRyhCb5lLUO41TiXKD3MBNj0lMqzS7ZdX7bnEnkqb2mW33QV6cTpBSiIJyVp1wC6fA=
  keep-history: false
  skip_cleanup: true
  file:
    - 'dist/*.tar.gz'
    - 'dist/*.zip'
  file_glob: true
  on:
    tags: true
